import type { ApiTool } from "./types";

export const apiTools: ApiTool[] = [
  {
    id: "send-text",
    group: "Mensagens",
    label: "Enviar texto",
    method: "POST",
    path: "/api/sessions/{sid}/messages/text",
    description: "Envia uma mensagem de texto comum.",
    sample: { to: "5511999999999", text: "Teste enviado pelo Manager v2" },
    availability: "current",
  },
  {
    id: "send-image",
    group: "Mensagens",
    label: "Enviar imagem",
    method: "POST",
    path: "/api/sessions/{sid}/messages/image",
    description: "Envia imagem por URL ou base64.",
    sample: {
      to: "5511999999999",
      url: "https://example.com/image.jpg",
      caption: "Imagem de teste",
      mimetype: "image/jpeg",
    },
    availability: "current",
  },
  {
    id: "send-audio",
    group: "Mensagens",
    label: "Enviar áudio",
    method: "POST",
    path: "/api/sessions/{sid}/messages/audio",
    description: "Envia áudio comum ou PTT por URL/base64.",
    sample: {
      to: "5511999999999",
      url: "https://example.com/audio.ogg",
      mimetype: "audio/ogg; codecs=opus",
      ptt: true,
    },
    availability: "current",
  },
  {
    id: "send-video",
    group: "Mensagens",
    label: "Enviar vídeo",
    method: "POST",
    path: "/api/sessions/{sid}/messages/video",
    description: "Envia vídeo por URL ou base64.",
    sample: {
      to: "5511999999999",
      url: "https://example.com/video.mp4",
      caption: "Vídeo de teste",
      mimetype: "video/mp4",
    },
    availability: "current",
  },
  {
    id: "send-document",
    group: "Mensagens",
    label: "Enviar documento",
    method: "POST",
    path: "/api/sessions/{sid}/messages/document",
    description: "Envia documento por URL ou base64.",
    sample: {
      to: "5511999999999",
      url: "https://example.com/document.pdf",
      fileName: "document.pdf",
      mimetype: "application/pdf",
    },
    availability: "current",
  },
  {
    id: "send-sticker",
    group: "Mensagens",
    label: "Enviar sticker",
    method: "POST",
    path: "/api/sessions/{sid}/messages/sticker",
    description: "Envia um sticker WebP por URL ou base64.",
    sample: {
      to: "5511999999999",
      url: "https://example.com/sticker.webp",
      mimetype: "image/webp",
    },
    availability: "current",
  },
  {
    id: "send-button",
    group: "Interativas",
    label: "Enviar botões",
    method: "POST",
    path: "/api/sessions/{sid}/messages/button",
    description: "Envia botões de resposta ou CTA de copiar, URL e chamada.",
    sample: {
      to: "5511999999999",
      title: "Escolha uma opção",
      text: "Mensagem interativa",
      footer: "AstraCalls",
      buttons: [
        { id: "option-1", text: "Opção 1", type: "reply" },
        { id: "option-2", text: "Opção 2", type: "reply" },
      ],
    },
    availability: "current",
  },
  {
    id: "send-list",
    group: "Interativas",
    label: "Enviar lista",
    method: "POST",
    path: "/api/sessions/{sid}/messages/list",
    description: "Envia uma lista interativa de seleção única.",
    sample: {
      to: "5511999999999",
      title: "Menu",
      text: "Selecione um item",
      footer: "AstraCalls",
      buttonText: "Abrir menu",
      sections: [
        {
          title: "Opções",
          rows: [{ id: "row-1", title: "Item 1", description: "Descrição" }],
        },
      ],
    },
    availability: "current",
  },
  {
    id: "send-location",
    group: "Interativas",
    label: "Enviar localização",
    method: "POST",
    path: "/api/sessions/{sid}/messages/location",
    description: "Envia latitude, longitude, nome e endereço.",
    sample: {
      to: "5511999999999",
      latitude: -23.55052,
      longitude: -46.633308,
      name: "Local de teste",
      address: "São Paulo - SP",
    },
    availability: "current",
  },
  {
    id: "send-contact",
    group: "Interativas",
    label: "Enviar contato",
    method: "POST",
    path: "/api/sessions/{sid}/messages/contact",
    description: "Envia um cartão de contato no formato vCard.",
    sample: {
      to: "5511999999999",
      contact: {
        fullName: "Contato de teste",
        phone: "5511888888888",
        organization: "AstraCalls",
      },
    },
    availability: "current",
  },
  {
    id: "send-poll",
    group: "Interativas",
    label: "Enviar enquete",
    method: "POST",
    path: "/api/sessions/{sid}/messages/poll",
    description: "Envia uma enquete com duas ou mais opções.",
    sample: {
      to: "5511999999999",
      question: "Qual opção você prefere?",
      options: ["Opção A", "Opção B"],
      selectableCount: 1,
    },
    availability: "current",
  },
  {
    id: "send-reaction",
    group: "Interativas",
    label: "Enviar reação",
    method: "POST",
    path: "/api/sessions/{sid}/messages/reaction",
    description: "Adiciona ou remove a reação de uma mensagem existente.",
    sample: {
      chat: "5511999999999@s.whatsapp.net",
      messageId: "MESSAGE_ID",
      emoji: "👍",
      fromMe: false,
    },
    availability: "current",
  },
  {
    id: "start-call",
    group: "Chamadas",
    label: "Iniciar chamada",
    method: "POST",
    path: "/api/sessions/{sid}/calls",
    description: "Inicia uma chamada de voz de saída.",
    sample: { phone: "5511999999999", duration_ms: 0, record: false },
    availability: "current",
  },
  {
    id: "call-history",
    group: "Chamadas",
    label: "Histórico de chamadas",
    method: "GET",
    path: "/api/sessions/{sid}/history",
    description: "Consulta o histórico recente da sessão.",
    availability: "current",
  },
  {
    id: "get-webhook",
    group: "Integrações",
    label: "Consultar webhook",
    method: "GET",
    path: "/api/sessions/{sid}/webhook",
    description: "Mostra a URL de webhook configurada na sessão.",
    availability: "current",
  },
  {
    id: "set-webhook",
    group: "Integrações",
    label: "Configurar webhook",
    method: "POST",
    path: "/api/sessions/{sid}/webhook",
    description: "Salva a URL que receberá os eventos da sessão.",
    sample: { url: "https://example.com/webhooks/whatsapp" },
    availability: "current",
  },
];
